apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{ include "betbot.labels" . | nindent 4 }}
    helm.sh/chart: {{ include "betbot.chart" . }}
  name: {{ template "betbot.fullname" . }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: {{ .Values.betbot.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "betbot.labels" . | nindent 12 }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{ toYaml . | nindent 12 }}
          {{- end }}
        spec:
          containers:
            - name: {{ include "betbot.name" . }}
              image: {{ include "betbot.image" . }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: LOGIN_TOKEN
                  {{- with .Values.betbot.loginToken }}
                  {{- if and (not (eq .existingSecret.secretName "")) (not (eq .existingSecret.secretKey "")) }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ .existingSecret.secretName }}
                      key: {{ .existingSecret.secretKey }}
                  {{- else }}
                  value: {{ .value }}
                  {{- end }}
                  {{- end }}
              args:
                - "--use-login-token"
                - $LOGIN_TOKEN
                {{- if .Values.betbot.dryRun }}
                - "--dry-run"
                {{- end }}
                {{- if .Values.betbot.overrideBets }}
                - "--override-bets"
                {{- end }}
                {{- if .Values.betbot.predictor }}
                - "--predictor"
                - {{ .Values.betbot.predictor }}
                {{- end }}
                - {{ .Values.betbot.community | quote }}
              {{- with .Values.resources }}
              resources:
                {{ toYaml . | nindent 14 }}
              {{- end }}

          restartPolicy: {{ .Values.restartPolicy }}

          {{- with .Values.affinity }}
          affinity:
            {{ toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{ toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.securityContext }}
          securityContext:
            {{ toYaml . | nindent 12 }}
          {{- end }}
