# This sets the container image. More information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/mrsteakhouse/betbot
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/ 
podAnnotations: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

affinity: {}

restartPolicy: Never

ttlSecondsAfterFinished: 300
# The number of seconds to keep any finished jobs

betbot:
  schedule: "0 10 * * 1,5"
  # Configure the  cronjob when the script should run

  community: ""
  # Enter your community you want to bet for

  predictor: "CalculationPredictor"
  # Use a specific predictor.
  # Allowed values are
  # - CalculationPredictor
  # - SimplePredictor
  # - ChatGPTPredictor
  # - PoissonPredictor

  dryRun: false
  # Only print log messages

  overrideBets: false
  # Override already entered bets

  loginToken:
  # Configure the login token to use
    value: ""
    # Set the value of the login token directly.

    existingSecret:
    # Use an existing secret to fetch the login token from.
      secretName: ""
      secretKey: ""

  # If you wish to use the ChatGPTPredictor, specify your API Key
  openai:
    value: ""
    existingSecret:
    # Use an existing secret to fetch the API key from.
      secretName: ""
      secretKey: ""