name: helm-chart

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@4.1.0
        with:
          useOCIRegistry: true
          registry-url: oci://ghcr.io/${{ github.repository }}
          username: mrsteakhouse
          access-token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
          force: true
          chart-folder: chart