name: docker-image

on:
  push:
    branches:
      - main
jobs:
  version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.appVersion.outputs.version }}
    steps:
      - uses: paulhatch/semantic-version@v5.4.0
        name: Application Version
        id: appVersion
        with:
          tag_prefix: "v"
          major_pattern: "(feat)"
          minor_pattern: "(fix)"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          bump_each_commit: 'true'
          debug: false

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set app version
        run: |
          sed -i 's/^\(appVersion: \).*$/\1${{ steps.appVersion.outputs.version }}/gm' charts/betbot/Chart.yaml

      - name: Commit app version
        if: steps.appVersion.outputs.changed
        continue-on-error: true
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am "update app version"
          git push

  docker:
    needs:
      - version
    environment: docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/mrsteakhouse/betbot:latest
            ghcr.io/mrsteakhouse/betbot:${{ needs.version.outputs.version }}

  tag:
    needs:
      - version
      - docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create App Tag
        run: |
          git tag ${{ needs.version.outputs.version }}
          git push origin --tags

  chartVersion:
    needs:
      - version
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: paulhatch/semantic-version@v5.4.0
        name: Chart Version
        id: chartVersion
        with:
          tag_prefix: "betbot-"
          major_pattern: "(feat)"
          minor_pattern: "(fix)"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          change_path: "charts"
          bump_each_commit: 'true'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set chart version
        run: |
          sed -i 's/^\(version: \).*$/\1${{ steps.chartVersion.outputs.version }}/gm' charts/betbot/Chart.yaml

      - name: Commit chart version
        if: steps.chartVersion.outputs.changed
        continue-on-error: true
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am "update chart version"
          git push

  chart:
    needs:
      - docker
      - chartVersion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set git config
        continue-on-error: true
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"